version: '3'
volumes:
  data:
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: soc_db
    ports:
      - "5432:5432"

